### ISSUE TITLE
Samsung control

### ISSUE THREAD

**Issue by giuseppebaldi** [schilea/ccwgtv-remote-card#1]
This is a great card, thank you. I got the webostv commands working great on my LG TV but how would I do the same with a Samsung? Here is the integration page for their smart TVs: https://www.home-assistant.io/integrations/samsungtv/

I tried changing domain to samsung or samsungtv but that didn't work.

**Comment by schilea** [comment]
Hi. I don't have a Samsung TV to test but I think you should use as domain remote and not samsung or samsungtv. It should be something like:

```
volume_up:
domain: remote
service: send_command
service_data:
  entity_id: remote.samsungtv
  command: KEY_VOLUP

```

**Comment by giuseppebaldi** [comment]
I will try that, thank you!

**Comment by giuseppebaldi** [comment]
BTW, I had mixed results with that. It works for volume up but for volume down and mute I get an error stating "Failed to perform the action remote/send_command. extra keys not allowed @ data['button']"
```
volume_down:
      domain: remote
      service: send_command
      service_data:
        entity_id: remote.samsung_6_series_55
        button: KEY_VOLDOWN
    volume_up:
      domain: remote
      service: send_command
      service_data:
        entity_id: remote.samsung_6_series_55
        command: KEY_VOLUP
    volume_mute:
      domain: remote
      service: send_command
      service_data:
        entity_id: remote.samsung_6_series_55
        button: KEY_MUTE
```
