### ISSUE TITLE
Buttons don't work with default config

### ISSUE THREAD

**Issue by Momro** [schilea/ccwgtv-remote-card#2]
Hi buddy,

first, this card is *awesome* and exactly what I need! Now I'm trying to set this up but nothing will happen.

For simplicity, I only started with up/down, so my code looks like this:

```
type: custom:ccwgtv-remote-card
scale: 1.2
up: 
domain: remote
service: send_command
service_data:
  entity_id: remote.chromecast
  command: DPAD_UP
down:
domain: remote
service: send_command
service_data:
  entity_id: remote.chromecast
  command: DPAD_DOWN
```

When I hit the save button and return to the code, the `down` section will be competely gone, and a `null` will be appended after `up`.

Anyway, the `up`-button doesn't work either, so I basically have nothing in the card that is working :-(

When I go to the dev tools, actions, and enter this code, the chromecast/remote will perform a `DPAD_DOWN`:

```
action: remote.send_command
data:
  num_repeats: 1
  delay_secs: 0.4
  hold_secs: 0
  command: DPAD_DOWN
target:
  entity_id: remote.chromecast
```

Any idea what is wrong here?

**Comment by schilea** [comment]
Hi. maybe could be related to code formatting/alignment? Seems there was an error in the code displayed in the description, I've just corrected it.
```
type: custom:ccwgtv-remote-card
title: CCwGTV Remote
scale: 1.2
up:
  domain: remote
  service: send_command
  service_data:
    entity_id: remote.chromecast
    command: DPAD_UP
down:
  domain: remote
  service: send_command
  service_data:
    entity_id: remote.chromecast
    command: DPAD_DOWN

```
